project:
  type: website
  output-dir: docs

format:
  html:
    mainfont: "Roboto"
    monofont: "Roboto Mono"
    css: |
      @import url('https://fonts.googleapis.com/css2?family=Roboto+Mono:ital,wght@0,100..700;1,100..700&family=Roboto:ital,wght@0,100..900;1,100..900&display=swap');
      body {
        font-family: "Roboto", sans-serif;
      }
      code, pre {
        font-family: "Roboto Mono", monospace;
      }